Feature/increase output UI size
cboard-org/cboard pull request #1173
Opened 2022-04-05 21:01 UTC by tomivm

related to #974

2022-04-07 20:09 UTC, RodriSanchez1 requested changes

2022-04-07 20:09 UTC, RodriSanchez1 commented on src/components/Board/Output/SymbolOutput/SymbolOutput.css
> +.Output__button__sm {
add the button tag before .Output_button__sm like the others classes

2022-04-07 20:09 UTC, RodriSanchez1 commented on src/components/Board/Output/SymbolOutput/ClearButton/ClearButton.js
> +export default withStyles(null)(ClearButton);
You can export directly the componente without the withStyles, like `export default (ClearButton)` and also deleate the import.

2022-04-07 20:09 UTC, RodriSanchez1 commented on src/components/Board/Output/SymbolOutput/ClearButton/ClearButton.js
> +export default withStyles(null)(ClearButton);
You can export directly the componente without the withStyles, like `export default (ClearButton)` and also deleate the import.

2022-04-07 20:11 UTC, RodriSanchez1 commented on src/components/Board/Output/SymbolOutput/ClearButton/ClearButton.js
> +    const { classes, hidden, increaseOutputButtons, ...other } = this.props;
You can delete the prop classes

2022-04-08 12:39 UTC, tomivm commented on src/components/Board/Output/SymbolOutput/SymbolOutput.css
> +.Output__button__sm {
why?

2022-05-03 18:16 UTC, martinbedouret requested changes
` Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
`

2022-05-04 02:09 UTC, martinbedouret approved these changes

2022-05-04 02:10 UTC, merged