Android - Add admob ads
cboard-org/cboard pull request #1186
Opened 2022-04-28 21:26 UTC by RodriSanchez1

Needs to add admob plugin and cordova-android-play-services-gradle-release plugin [Ccboard PR](https://github.com/cboard-org/ccboard/pull/28)

2022-05-04 17:05 UTC, tomivm commented on src/components/Board/Board.container.js
> +      await this.handleAdMobAds();
I think that is not necessary to await during ad loading. Considering that is not showing on this component.

2022-05-06 13:01 UTC, martinbedouret requested changes

2022-05-06 13:01 UTC, martinbedouret commented on src/components/Board/Board.container.js
> +      .catch(msg => console.log('Error load interstitial Ad', msg));
use `console.error` instead

2022-05-06 13:01 UTC, martinbedouret commented on src/components/Settings/Settings.container.js
> +        .catch(msg => console.log('The interstitial advice is not available'));
use `console.error` instead

2022-05-06 13:01 UTC, martinbedouret commented on src/components/Settings/Settings.container.js
> +        .catch(msg => console.log('The banner advice is not available'));
use `console.error` instead

2022-05-06 13:01 UTC, martinbedouret commented on src/cordova-util.js
> +        console.log(err.message);
use `console.error` instead

2022-05-06 15:12 UTC, martinbedouret approved these changes

2022-05-06 15:12 UTC, merged

2022-05-06 15:12 UTC, RodriSanchez1 commented
resolve #1204