Persistence of Arasaac symbols when device is offline
cboard-org/cboard pull request #1237
Opened 2022-07-07 20:14 UTC by tomivm

2022-07-15 23:47 UTC, martinbedouret requested changes

2022-07-15 23:47 UTC, martinbedouret commented on src/components/Board/SymbolSearch/SymbolSearch.component.js
> +  handleSuggestionSelected = async (event, { suggestion }) => {
I don't think this is the right place to make the update, as you will be updating all the suggestions (including global symbols). You should make the update on the fetch arasaac suggestions level.

2022-07-16 00:57 UTC, martinbedouret approved these changes

2022-07-16 00:57 UTC, merged

2022-09-07 18:22 UTC, RodriSanchez1 commented
#resolve #1067