Feature/fix touch bug
cboard-org/cboard pull request #1264
Opened 2022-09-23 11:03 UTC by vlaco

The bug with multi touch was fixed by installing hammerjs library. Please test if everything is still working properly.

2022-09-27 18:44 UTC, martinbedouret commented
@vlaco Thanks for this. Is there an open issue with the bug?
Please remove lock files from the PR.
@tomivm Could you please do the review for this?

2022-09-29 16:05 UTC, tomivm commented
thanks @vlaco ! please link the issue that you are resolving.
About the testing. 
Tiles aren't rendered and I receive the following errors on the console:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Board`. See https://reactjs.org/link/warning-keys for more information.
```
and

`Warning: Failed prop type: Duplicate child key "null" found! This will cause problems in ReactGridLayout.`

2022-09-29 17:22 UTC, tomivm requested changes

2022-09-29 17:22 UTC, tomivm commented on src/components/Board/Board.component.js
> -        <div key={tile.id}>
The key is necessary. See https://reactjs.org/docs/lists-and-keys.html

2022-10-03 14:50 UTC, vlaco commented
> @vlaco Thanks for this. Is there an open issue with the bug? Please remove lock files from the PR. @tomivm Could you please do the review for this?

@martinbedouret this is an attempt to resolve this issue

2022-10-06 02:42 UTC, RodriSanchez1 commented
Hi! @vlaco and @matijavibe! Thanks for been part of these amazing project!
I just tested in web and android device. In touch devices when you try to scroll the board view the tapped tile is pressed.  You will need to treat the pan event.

2022-10-06 15:33 UTC, tomivm commented
I note the same as @RodriSanchez1 . When the users scroll the board tiles are pressed. Also, this PR eliminates the possibility of selecting tiles with the scanner feature and the feature of navigating fixed boards with the arrow keys is damaged too.

2023-06-01 10:58 UTC, vlaco commented
In order to solve this a refactor of the whole app is needed

2025-03-18 15:25 UTC, closed without merging