Implement UI indicating that Internet connection is necessary to search new ARASAAC and Global Symbols #1268
cboard-org/cboard pull request #1295
Opened 2022-11-17 01:44 UTC by yehwang1

2022-11-17 02:16 UTC, yehwang1 commented
We are currently writing tests for this new feature and we are pushing this initial PR for review in the meantime. We plan to update this PR with tests within one week.

2022-11-19 22:18 UTC, martinbedouret requested changes
@yehwang1 Thanks for your fix! Some comments BELOW: 

- For the notifications to the users, please use the notification component we use throughout the entire application to be compliant with the material design principles https://m2.material.io/design/introduction
- The notification should be a warning type 
- The text message must be taken from a message file and included in the cboard.json for translations. 

@tomivm can you help with this review?

2022-11-21 13:43 UTC, tomivm commented
Hi! it's a pleasure.
To show a Notification should pass the "showNotification" action from Board.container (Board.container.js:1667) through "TileEditor" and "SymbolSearch" components via props.
With the objective to show a 'warning' notification. Send the message on the first argument and a 'warning' string on the second argument. I will create that kind of notification for this PR
It should show the notification only after the 'SymbolSearch' component is mounted and the app is not connected to the internet.
The notification message should be similar to 'Available symbols are limited during editing offline'. please @martinbedouret review this message.
The message would be included on src/translations/src/cboard.json and on the src/components/Board/SymbolSearch/SymbolSearch.messages.js
Should use intl.formatMessage() with the message like an argument for `showNotification()` to display it. See this line as an example: https://github.com/cboard-org/cboard/blob/1ea47033f162aa8581a4bbd36e3c7b729e750d53/src/components/Analytics/Analytics.container.js#L89
Let me know if you need some help! you can contact me on discord tomivm#2865

2022-11-21 21:09 UTC, yehwang1 commented
Hi Martin and Tom, thank you for leaving such great feedback! My partner and I will address your suggestions and give an update in about 1.5 weeks from now. Thank you!

2022-12-08 18:21 UTC, tomivm requested changes

2022-12-08 18:21 UTC, tomivm commented on src/components/Board/TileEditor/TileEditor.component.js
> +            intl={this.props.intl}
this prop is never used.

2022-12-08 18:21 UTC, tomivm commented on src/components/Board/SymbolSearch/SymbolSearch.css
> +  /* z-index: 0; */
this change is necessary?

2022-12-08 18:21 UTC, tomivm commented on src/components/Board/SymbolSearch/SymbolSearch.css
> +    top: 170px;
why this change?

2022-12-08 18:21 UTC, tomivm commented on src/components/Board/SymbolSearch/SymbolSearch.css
> +#offlineMsg {
this is never used

2022-12-08 18:21 UTC, tomivm commented on src/components/UI/FilterBar/FilterBar.css
> +  margin-top: 10px;
this change is not necessary

2022-12-08 18:26 UTC, tomivm requested changes

2022-12-08 18:26 UTC, tomivm commented on src/components/Board/TileEditor/TileEditor.test.js
> +    wrapper.find('.hello').simulate('click');
the new tests are failling 
```FAIL  src/components/Board/TileEditor/TileEditor.test.js (46.4s)
  ● TileEditor tests › should render notification if offline

    Method “simulate” is meant to be run on 1 node. 0 found instead.

      91 |     console.log(wrapper.debug());
      92 |
    > 93 |     wrapper.find('.hello').simulate('click');
         |                            ^
      94 |     console.log('BUTTON CLICKED');
      95 |     console.log(wrapper.debug());
      96 |     // expect(onButtonClick).to.have.property('callCount', 1);

      at ShallowWrapper.single (node_modules/enzyme/src/ShallowWrapper.js:1652:13)
      at ShallowWrapper.simulate (node_modules/enzyme/src/ShallowWrapper.js:1133:17)
      at Object.<anonymous> (src/components/Board/TileEditor/TileEditor.test.js:93:28)
```

2022-12-08 18:26 UTC, tomivm commented on src/components/Board/TileEditor/TileEditor.test.js
> +    console.log(wrapper.debug());
remove console.log 's

2023-03-05 20:04 UTC, closed without merging

2023-03-05 20:04 UTC, martinbedouret commented
closed due to inactivity