Feature / default boards options mananger
cboard-org/cboard pull request #1324
Opened 2022-12-19 21:16 UTC by tomivm

2022-12-20 20:28 UTC, RodriSanchez1 commented on src/components/Communicator/CommunicatorToolbar/CommunicatorToolbar.messages.js
> +      'If you accept. this action changes your home board to the selected option. You can switch it again by selecting another option.'
Do you want to change your home board for the selected option? You can switch it again by selecting another option.'

2022-12-20 20:28 UTC, RodriSanchez1 commented on src/components/Communicator/CommunicatorToolbar/DefaultBoardSelector/DefaultBoardOption.js
> +        width: { xs: '100%' }
You can add the property `cursor: 'pointer'` for better styling

2022-12-20 20:28 UTC, RodriSanchez1 commented on src/reducers.js
> +  migrate: createMigrate(boardMigrations, { debug: true })
change to  `{debug: false}`

2022-12-20 20:28 UTC, RodriSanchez1 commented on src/translations/src/cboard.json
> +  "cboard.components.CommunicatorToolbar.confirmChangeHomeBoardMessage": "If you accept. this action changes your home board to the selected option. You can switch it again by selecting another optio
Update according to the new message

2022-12-20 20:47 UTC, RodriSanchez1 commented
Needs to add the prop `defaultBoardIncluded ` on the intitial state of the communicator reducer

2022-12-20 21:50 UTC, tomivm commented on src/components/Communicator/CommunicatorToolbar/DefaultBoardSelector/DefaultBoardOption.js
> +        width: { xs: '100%' }
I don't agree. Probably would be better to add a hover style.
see: https://www.youtube.com/watch?v=AnTNN_QlFvQ&t=10s

2022-12-20 22:44 UTC, RodriSanchez1 commented on src/components/Communicator/CommunicatorToolbar/DefaultBoardSelector/DefaultBoardOption.js
> +        width: { xs: '100%' }
Yeah! You can add whatever you want!

2022-12-21 16:13 UTC, tomivm commented
> Needs to add the prop `defaultBoardIncluded ` on the intitial state of the communicator reducer

@RodriSanchez1  Are you sure that this is necessary? in principle this is intentional because the feature is designed to support old users. If the user not has default boards included and uses the feature. The communicator home board (that probably is already modified) is stored for the 'advanced' homeBoard.
Do you think that this could cause a bug?

2022-12-22 19:25 UTC, tomivm commented
To improve the first usage of the app the default boards gallery should be integrated into the first dialog of  the boardTour
![image](https://user-images.githubusercontent.com/21298844/209211238-00dfaba2-93f4-4b12-bcce-b8bcdec0ad45.png)

2022-12-22 21:43 UTC, martinbedouret requested changes

2022-12-22 21:43 UTC, martinbedouret commented on package.json
> +    "@mui/material": "^5.11.0",
We should not use the mui packages until we update the material UI version on cboard.

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Board/Board.messages.js
> +  },
change to `Here you can switch between different featured boards`

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Communicator/Communicator.constants.js
> +export const PUSH_DEFAULT_BOARD_INCLUDED =
not clear what is `PUSH` in this context. Shouldn't be `ADD`?

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Communicator/CommunicatorToolbar/CommunicatorToolbar.messages.js
> +    defaultMessage: 'Default boards selector'
change to `Select a featured board`

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Communicator/CommunicatorToolbar/CommunicatorToolbar.messages.js
> +    defaultMessage: 'Select a default board'
change to `Select a featured board`

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Communicator/CommunicatorToolbar/CommunicatorToolbar.messages.js
> +      'Do you want to change your home board for the selected option? You can switch it again by selecting another option.'
change to `Do you want to change your current board for the selected option? You can switch it again`

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Communicator/CommunicatorToolbar/CommunicatorToolbar.messages.js
> +    defaultMessage: 'Default board caption'
Change to `Board caption`

2022-12-22 21:43 UTC, martinbedouret commented on src/components/Communicator/CommunicatorToolbar/DefaultBoardSelector/DefaultBoardOption.js
> +import { Card, CardMedia, Typography } from '@mui/material';
use the `material-ui` package

2022-12-23 01:42 UTC, tomivm commented on src/components/Communicator/Communicator.constants.js
> +export const PUSH_DEFAULT_BOARD_INCLUDED =
yes, it should be ADD! thanks

2022-12-26 21:27 UTC, martinbedouret approved these changes

2022-12-26 21:28 UTC, merged