Show password branch
cboard-org/cboard pull request #1463
Opened 2023-04-22 00:09 UTC by arjunanand23

Attempted to add feature where password could be shown/hidden. Currently works if another character is entered but does not take place immediately.

2023-04-26 16:03 UTC, martinbedouret commented
awesome @arjunanand23 !
@tomivm Could you please take a look?

2024-05-24 15:11 UTC, shayc commented on src/components/Account/Login/Login.component.js
> +                        onClick={() => { showPassword = !showPassword; }}
this line is problematic, updating a variable instead of state

2024-05-24 15:35 UTC, tomivm requested changes
Use State instead of a variable

2024-05-24 15:35 UTC, tomivm commented on src/components/Account/Login/Login.component.js
> +    var showPassword = false;
A state should be used for this. This is the reason why you need to type a new character to see the password.

2024-05-26 15:40 UTC, closed without merging

2024-05-27 11:55 UTC, tomivm commented
completed on #1700 PR