Fix / Get subscriber loop
cboard-org/cboard pull request #1539
Opened 2023-07-13 23:07 UTC by RodriSanchez1

2023-07-14 12:44 UTC, tomivm commented on src/components/PremiumFeature/PremiumFeature.js
> +    if (isUpdateSubscriptionNeeded(lastUpdated)) {
Probably would be good rename this function by something like "isUpdateIsSubscribedNeeded" or "isUpdateSubscriberStatusNeeded"

2023-07-14 12:45 UTC, tomivm commented
Please Add a Description :)

2023-07-18 19:38 UTC, martinbedouret requested changes

2023-07-18 19:38 UTC, martinbedouret commented on src/providers/SubscriptionProvider/SubscriptionProvider.container.js
'isCordova' is defined but never used

2023-07-18 19:38 UTC, martinbedouret commented on src/providers/SubscriptionProvider/SubscriptionProvider.reducer.js
> +  lastUpdated: null
use Unassigned instead of  null here

2023-07-19 21:44 UTC, martinbedouret approved these changes

2023-07-19 21:44 UTC, merged