Fix/dialogs behind keyboard on Android and IOS
cboard-org/cboard pull request #1557
Opened 2023-07-31 15:45 UTC by tomivm

This PR uses a newly added plugin to adjust welcome dialog sizes to not be covered by the keyboard on Android and IOS. Please @RodriSanchez1 can you Test it? Also, please use the keyboard with live mode to make sure the board is not resized.

2023-08-02 23:54 UTC, RodriSanchez1 approved these changes
Its a good feature! I like it a lot!

2023-08-02 23:54 UTC, RodriSanchez1 commented on src/components/WelcomeScreen/WelcomeScreen.container.js
> +  handlekeyboardDidHide = () => {
change `handlekeyboardDidHide`  to `handleKeyboardDidHide`  ( Camel case)

2023-08-02 23:54 UTC, RodriSanchez1 commented on src/components/WelcomeScreen/WelcomeScreen.container.js
> +    //const dialogContentWithKeyboardStyle = this.dialogContentStyle();
Remove unncesary comment

2023-08-03 00:20 UTC, RodriSanchez1 commented
Suggestion: 
- Add an scroll indicator on sign up dialog.  Needs to scroll to see the action buttons! 
Image on Samsung Galaxy Tab A7
![Screenshot_20230802-205517_AAC_Cboard 1](https://github.com/cboard-org/cboard/assets/80465873/65a2bc95-4646-4768-a4af-4028ed8041d3)

- Smartphones will have problems on rotated screen. But i think this is not a big problem, we can avoid it. See:

![Screenshot_20230802_205032_AAC Cboard](https://github.com/cboard-org/cboard/assets/80465873/77440b8f-2572-477d-ab16-1b2ccc9b10cd)

2023-08-11 18:25 UTC, martinbedouret requested changes
@tomivm Please review comments from rodri

2023-08-14 19:52 UTC, martinbedouret approved these changes

2023-08-14 19:53 UTC, merged