Fix/export boards on cordova ios
cboard-org/cboard pull request #1558
Opened 2023-08-04 18:41 UTC by tomivm

Add necessary changes to allow our Cordova IOS app to use the Export Boards feature. close #1459

2023-08-11 23:02 UTC, martinbedouret requested changes

2023-08-11 23:02 UTC, martinbedouret commented on src/components/Settings/Export/Export.helpers.js
> +        console.log(error);
replace by `console.error`

2023-08-11 23:02 UTC, martinbedouret commented on src/cordova-util.js
> +          const extractFileName = nameWithDirectorie => {
replace `nameWithDirectorie` by `nameWithDirectory`

2023-08-11 23:02 UTC, martinbedouret commented on src/cordova-util.js
> +            const lastIndex = nameParts.length - 1;
use `lastIndexOf()` method 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf

2023-08-14 18:19 UTC, RodriSanchez1 approved these changes

2023-08-15 02:38 UTC, martinbedouret approved these changes

2023-08-15 02:38 UTC, merged