Transform receipt on purchase validator
cboard-org/cboard pull request #1610
Opened 2023-11-06 22:42 UTC by RodriSanchez1

On this PR:

- The receipt object retrieved from the cordova-purchase-plugin needs to be transformed to support the new version 13.8.6.  See the ccboard [PR](https://github.com/cboard-org/ccboard/pull/71)

2023-11-07 15:42 UTC, tomivm requested changes

2023-11-07 15:42 UTC, tomivm commented on src/providers/SubscriptionProvider/SubscriptionProvider.container.js
> +    const transformReceipt = this.transformReceipt;
The only use of tranformReceipt is inside configPurchaseValidator function. Declare the function tranformReceipt inside of this scope and avoid the use of 'this'.

2023-11-07 15:42 UTC, tomivm commented on src/providers/SubscriptionProvider/SubscriptionProvider.container.js
> +        const transaction = transformReceipt(receipt);
Please avoid changes on IOS platform and make the changes only for Android.

2023-12-12 13:40 UTC, martinbedouret approved these changes

2023-12-12 13:42 UTC, merged