Feature / Font size selector on PDF export
cboard-org/cboard pull request #1612
Opened 2023-11-13 10:05 UTC by chelsouse

PR for issue #1575

2023-11-15 00:44 UTC, RodriSanchez1 requested changes
@chelsouse Nice work!! Take a look at the comments that i made! Let me now if you have some doubts!

2023-11-15 00:44 UTC, RodriSanchez1 commented on src/components/Settings/Export/Export.component.js
> +      exportAllBoardSize: '16',
A better variable name can be `labelFontSize` or something more descriptive

2023-11-15 00:44 UTC, RodriSanchez1 commented on src/components/Settings/Export/Export.component.js
> +                        <MenuItem value="12">Small</MenuItem>
Add ´Small´, ´Medium´ and ´Large´ words to the ´Export.messages.js´ to get the translations 

Use this values instead:
 - Small: 9
 - Medium: 12
 - Large: 16

Remember to update the default value on the state definition! Line 42

2023-11-15 00:44 UTC, RodriSanchez1 commented on src/components/Settings/Export/Export.component.js
> +              <Divider />
Im thinking we can improve it. Take a look at this: 
![image](https://github.com/cboard-org/cboard/assets/80465873/16dbb876-c36b-4403-8150-910982daa5e5)

What do you think? You can investigate on the `Settings.component.js`

2023-11-15 00:44 UTC, RodriSanchez1 commented on src/components/Settings/Export/Export.helpers.js
> +    //exportAllBoardSize = exportAllBoardSize - 4;
remove the comment!

2023-11-15 00:44 UTC, RodriSanchez1 commented on src/components/Settings/Export/Export.helpers.js
> +    fontSize: exportAllBoardSize,
See line 643  - 
`if (imageData.width <= 37) {
    labelData.fontSize = 7;
  } else if (imageData.width <= 40) {
    labelData.fontSize = 8;
  } else if (imageData.width <= 45) {
    labelData.fontSize = 9;
  }`

We need to manage also this!

2023-11-15 16:30 UTC, chelsouse commented
Hello @RodriSanchez1

I've implemented the requested changes. Please let me know, if it needs any futher changes.

2023-11-16 21:31 UTC, RodriSanchez1 approved these changes
@chelsouse Nice workk!  I made a few changes, check it out! 

I want to give you a little advice, in your future commits try to implement atomic commits. This way, your work will be more detailed. An also always add a PR description!

See:
_[What's an atomic git commit?](https://dev.to/samuelfaure/how-atomic-git-commits-dramatically-increased-my-productivity-and-will-increase-yours-too-4a84)
Working with atomic git commits means your commits are of the smallest possible size. Each commit does one, and only one simple thing, that can be summed up in a simple sentence.
The amount of code change doesn't matter. It can be a letter or it can be a hundred thousand lines, **but you should be able to describe the change with one simple short sentence.**_

Hope you want continue contributing on Cboard! 
Regards, Rodri!

2023-11-16 21:35 UTC, merged

2023-11-17 16:24 UTC, chelsouse commented
Hello @RodriSanchez1 

Thanks for your help and advice on atomic commits! It's my first PR, and I'll definitely keep your suggestions in mind. Appreciate the guidance!