add loading spinner on upload image
cboard-org/cboard pull request #1622
Opened 2023-11-24 13:15 UTC by rakeshkumar1019

On this PR new loading spinner is added on`TileEditor.component `. It will be displayed when the image is loading.
Spinner is used from  [progress MUI v4](https://v4.mui.com/components/progress/#progress)

see this screenshot for the reference. 
<img width="682" alt="Screenshot 2023-11-24 at 6 41 43 PM" src="https://github.com/cboard-org/cboard/assets/52422856/8f34675c-ceca-49c5-a5f0-f5c3ed08e670">

close #1614

2023-11-27 19:33 UTC, RodriSanchez1 requested changes
Hi! @rakeshkumar1019 Thank for your contribution! Your work is well! But the spinner will be not displayed when the app is proccesing the image. The inItial change of the loading state needs to be under  the `InputImage.component.js`.  Let me know if you need a further explanation 🙌

2023-11-27 19:33 UTC, RodriSanchez1 commented on src/components/Board/TileEditor/TileEditor.component.js
> +      loading: false
Change the prop name to `isLoading`

2023-11-28 06:12 UTC, rakeshkumar1019 commented on src/components/Board/TileEditor/TileEditor.component.js
> +      loading: false
Hi @RodriSanchez1  Thanks for acknowledging the pr & changes are made as requested.kindly review it.

2023-12-08 19:01 UTC, martinbedouret commented
@RodriSanchez1  let me know if this can be merged

2023-12-11 19:49 UTC, RodriSanchez1 approved these changes

2023-12-12 01:07 UTC, merged