added PasswordTextField component  fixed #1702
cboard-org/cboard pull request #1709
Opened 2024-06-14 04:28 UTC by KirtiKamal

added PasswordTextField component

2024-06-14 14:00 UTC, RodriSanchez1 requested changes
Good work! Use this component on the LogIn form also!

2024-06-14 14:05 UTC, RodriSanchez1 commented on src/components/Account/SignUp/SignUp.component.js
> +                    label={intl.formatMessage(messages.password)}
Change to `label={intl.formatMessage(messages.createYourPassword)}`

2024-06-14 14:05 UTC, RodriSanchez1 commented on src/components/Account/SignUp/SignUp.component.js
> +                    label={intl.formatMessage(messages.confirmPassword)}
Change to `label={intl.formatMessage(messages.confirmYourPassword)}`

2024-06-14 14:05 UTC, RodriSanchez1 commented on src/components/Account/SignUp/SignUp.component.js
> +                    name="confirmPassword"
Change to `name="passwordConfirm"`

2024-06-14 14:05 UTC, RodriSanchez1 commented on src/components/Account/SignUp/SignUp.component.js
> +                    error={errors.confirmPassword}
change to `error={errors.passwordConfirm}`

2024-06-15 04:42 UTC, KirtiKamal commented
@RodriSanchez1 I have fixed all the requested changes and added PasswordTextField on the Login component. Kindly review.

2025-03-18 15:41 UTC, RodriSanchez1 commented
@KevinDussel could you review and test this PR please?

2025-03-20 15:01 UTC, KevinDussel commented
> Great job! @KirtiKamal @KevinDussel could you review and test this PR please?

@RodriSanchez1 just reviewed the PR and the new PasswordTextField component is properly integrated  in signUp component and loginComponent .

2025-03-20 15:29 UTC, KevinDussel approved these changes
@RodriSanchez1 just reviewed the PR and the new PasswordTextField component is properly integrated in signUp component and loginComponent .

2025-03-20 15:57 UTC, KirtiKamal commented
@KevinDussel if everything is fine can you merge the PR

2025-03-20 17:25 UTC, merged