Arabic api
cboard-org/cboard pull request #405
Opened 2019-04-09 20:11 UTC by jtaco

Integrate tawasol API in case the current language is Arabic.

2019-04-10 16:43 UTC, martinbedouret requested changes

2019-04-10 16:43 UTC, martinbedouret commented on src/components/Board/Board.component.js
> +import BoardSpeedDial from './BoardSpeedDial';
These updates are related to a different feature , remove them from here

2019-04-10 16:43 UTC, martinbedouret commented on src/components/Board/BoardSpeedDial/BoardSpeedDial.css
> +.mobile-only {
These updates are related to a different feature , remove them from here

2019-04-10 16:43 UTC, martinbedouret commented on src/components/Board/BoardSpeedDial/BoardSpeedDial.js
> +import React, { Component } from 'react';
These updates are related to a different feature , remove them from here

2019-04-10 16:43 UTC, martinbedouret commented on src/components/Board/BoardSpeedDial/BoardSpeedDial.messages.js
> +import { defineMessages } from 'react-intl';
These updates are related to a different feature , remove them from here

2019-04-10 16:43 UTC, martinbedouret commented on src/constants.js
> +  'http://madaportal.org/tawasol/wp-json/custom/v2/dea44ade76/';
API token ID must be taken from an environment variable , remove it from here

2019-04-10 16:43 UTC, martinbedouret commented on src/components/Board/SymbolSearch/SymbolSearch.component.js
> +    let localSuggestions, srasaacSuggestions;
`srasaacSuggestions` typo??

2019-04-11 01:23 UTC, jtaco commented on src/components/Board/SymbolSearch/SymbolSearch.component.js
> +    let localSuggestions, srasaacSuggestions;
El problema es el uso de 'let'?

2019-04-11 18:39 UTC, martinbedouret approved these changes

2019-04-11 18:40 UTC, merged