[DO NOT MERGE] - Redux undo
cboard-org/cboard pull request #413
Opened 2019-04-13 19:25 UTC by gavinhenderson

Hey @shayc and @martinbedouret was wondering if you would like to take a look at my progress and give some feedback. Currently there is no undoing but the 'undo' button now appears on the notifications that it should. 

I added 'action' to the Notification component as that is what 'Snackbar' takes.

Thoughts?

2019-04-15 18:39 UTC, shayc commented on src/components/Board/Board.container.js
> +      <Button
I would refactor this `Button` component to its own `UndoButton` in our shared UI components folder. This seems generic enough and many components will want to use this and it's nice to isolate the translation there as well.

2019-04-15 18:39 UTC, shayc commented on src/components/Board/Board.container.js
> +      <Button
Into a single component `UndoButton`

2019-04-15 18:47 UTC, shayc requested changes
I like your direction, great start!

2019-04-15 18:47 UTC, shayc commented on src/components/Notifications/Notifications.container.js
> +    action: PropTypes.arrayOf(PropTypes.object)
type should be: `PropTypes.node`

```
  // Anything that can be rendered: numbers, strings, elements or an array
  // (or fragment) containing these types.
  optionalNode: PropTypes.node,
```

2019-04-15 18:47 UTC, shayc commented on src/components/Notifications/Notifications.component.js
> +  action: PropTypes.arrayOf(PropTypes.object),
Type should be: `PropTypes.node`

```
// Anything that can be rendered: numbers, strings, elements or an array
// (or fragment) containing these types.
optionalNode: PropTypes.node,
```

2019-04-15 18:47 UTC, shayc commented on src/components/Board/Board.messages.js
> +    id: 'cboard.components.Board.undo',
When refactoring to `UndoButton`, should update this string:
` id: 'cboard.components.UndoButton.undo'`

2019-04-16 13:16 UTC, gavinhenderson commented
@shayc Thanks for the feedback! I will make those changes and get the functionality working.

Ill close this PR just now and open a new one when im done

2019-04-16 15:08 UTC, closed without merging