Cordova support changes
cboard-org/cboard pull request #461
Opened 2019-08-07 11:36 UTC by nous-

CBoard changes to support Cordova while maintaining support for web. See [CCBoard repo](https://github.com/nous-/ccboard) for Cordova packaging built for CBoard.

TTS is supported with minimal changes by [phonegap-plugin-speech-synthesis](https://github.com/macdonst/SpeechSynthesisPlugin) plugin. See the README in the CCboard repo for more.

Open items:
1. Conditionally include Cordova required fields in `index.html` at build time depending on build target (Cordova or Web). Preferences on how we should do this?
1. Cordova file paths must be relative, not absolute. Existing boards use absolute image paths. When running on Cordova, all image paths are prepended with a `.` to correctly build a relative path. We may choose to update the data instead. Thoughts?
1. Should Cordova packaging (CCBoard) be merged into this repo?

2019-08-07 17:50 UTC, martinbedouret commented on src/components/Board/Symbol/Symbol.js
> +
for sure we will have to do the same thing in several other places as well

2019-08-08 18:11 UTC, martinbedouret requested changes

2019-08-08 18:11 UTC, martinbedouret commented on public/index.html
> +    default-src 'unsafe-inline' 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
this does not look good, this line contains duplicate directives (img-src),

2019-08-09 18:08 UTC, nous- commented on public/index.html
> +    img-src: https://www.googletagmanager.com
Great - I will add.

2019-08-09 18:10 UTC, martinbedouret commented on src/components/Board/Symbol/Symbol.js
> +
I can do the work here

2019-08-16 15:52 UTC, martinbedouret commented on public/index.html
> +    img-src: https://www.googletagmanager.com
I already have fixed it

2019-08-16 15:53 UTC, martinbedouret commented on public/index.html
> +    default-src 'unsafe-inline' 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
I already have fixed it

2019-08-16 15:53 UTC, martinbedouret commented on src/components/Board/Symbol/Symbol.js
> +
I already have fixed it

2019-08-16 15:56 UTC, martinbedouret approved these changes

2019-08-16 15:56 UTC, merged