Push dark theme
cboard-org/cboard pull request #671
Opened 2020-04-01 20:27 UTC by martinbedouret

2020-04-02 18:14 UTC, shayc commented
Heya, will review later today :)

2020-04-02 19:28 UTC, shayc requested changes
Overall looks good, the only issue I have is with the class names. I'll try to push to this branch and fix the issues myself. Good job man.

2020-04-02 19:28 UTC, shayc commented on src/components/Board/Navbar/Navbar.css
> +.Navbar__dark {
the class name should be `.Navbar--dark`.
We're using [B.E.M. class naming convention](https://css-tricks.com/bem-101/) - and dark is a modifier.

2020-04-02 19:28 UTC, shayc commented on src/components/Board/Navbar/Navbar.js
> +      <div className={classNames('Navbar', { Navbar__dark: dark }, className)}>
`Navbar__dark` to `Navbar--dark`

2020-04-02 19:28 UTC, shayc commented on src/components/Board/Output/SymbolOutput/SymbolOutput.css
> +.SymbolOutput__dark {
same...

2020-04-02 19:28 UTC, shayc commented on src/components/Communicator/CommunicatorDialog/CommunicatorDialog.component.js
> +            CommunicatorDialog__tabs__dark: dark
Instead of passing a dark class to all sub components of `CommunicatorDialog` you could place just one class on the component's root `div`

2020-04-02 19:43 UTC, shayc commented on src/components/Board/Output/SymbolOutput/SymbolOutput.js
> +import { dark } from '@material-ui/core/styles/createPalette';
Unused import - should be deleted

2020-04-02 19:54 UTC, shayc commented
@martinbedouret I fixed the stuff in the code review, it's in PR #672 
If you'll accept the changes, you'll need to merge that PR to this branch and then to master.

2020-04-03 15:34 UTC, martinbedouret commented
fantastic feedback @shayc !! I did apply a couple of fixes as well !

2020-04-03 15:38 UTC, merged