Re-style welcome and login pages
cboard-org/cboard pull request #699
Opened 2020-05-20 23:25 UTC by martinbedouret

![image](https://user-images.githubusercontent.com/8397930/82507130-d62ad980-9ad7-11ea-8efa-6418f91a6d57.png)

![image](https://user-images.githubusercontent.com/8397930/82507212-0d998600-9ad8-11ea-9ab1-af9c99b7dfd3.png)

2020-05-21 02:18 UTC, sylvansson requested changes
Love the new background 👌

2020-05-21 03:55 UTC, kidcompassion requested changes
This looks great, I love the animation! 😻 

The only issue I see is that the welcome panel is getting clipped, which seems to be coming from the padding on `.WelcomeScreen`, which then pushes the panel down, where it gets clipped by the `overflow:hidden` set on body, html. I _think_ if you turn it off, it'll work. 💯 

<img width="357" alt="Screen Shot 2020-05-20 at 9 50 34 PM" src="https://user-images.githubusercontent.com/1507827/82521531-2b6ce800-9ae4-11ea-8a42-fbbec8c7e3d2.png">

With padding: 
<img width="278" alt="Screen Shot 2020-05-20 at 9 53 20 PM" src="https://user-images.githubusercontent.com/1507827/82521621-5f480d80-9ae4-11ea-98db-df3a72f0ef23.png">

Without padding:
<img width="350" alt="Screen Shot 2020-05-20 at 9 49 52 PM" src="https://user-images.githubusercontent.com/1507827/82521635-696a0c00-9ae4-11ea-97f5-168fa76e3c49.png">

2020-05-23 13:04 UTC, sylvansson approved these changes

2020-05-24 16:18 UTC, martinbedouret commented on src/components/AuthScreen/AuthScreen.component.js
> +      <div className="AuthScreen__content">
Yes , I fixed it. thank you!

2020-05-24 16:20 UTC, martinbedouret commented
Thank you guys for the feedback! Appreciate

2020-05-24 16:20 UTC, merged