fix: color scheme for dark mode
cboard-org/cboard pull request #705
Opened 2020-05-29 23:46 UTC by shayc

fixes dark color scheme with symbols legibility

2020-05-30 23:38 UTC, martinbedouret requested changes
@shayc  fix for links looks great !
For the output bar I would rather take a different strategy: 

1. Replace the inline CSS of the SVG images by a class name 
2. Control the stroke color of the SVGs from CSS 

That will give us a lot of flexibility for the future in case we want to implement more themes or change the contrast of symbols for people with visual impairments. Here an example of the result:
![image](https://user-images.githubusercontent.com/8397930/83341073-7beaff00-a2b5-11ea-8904-22fa625d2816.png)

2020-05-30 23:40 UTC, martinbedouret commented
https://stackoverflow.com/questions/37940282/changing-the-stroke-color-for-an-inline-svg

2020-05-31 16:02 UTC, shayc commented
@martinbedouret your approach is better but we have a few obstacles: 

1) At the moment we use `<img src="example.svg"/>` to render SVG, this limits us technically from styling SVG with CSS. We can refactor the code to render with `<svg />` tags instead but other file formats (jpg/png) still need `<img />` tags to render and we wont be able to style them for dark theme, this will cause some of them to not be legible.

Example: 
![image](https://user-images.githubusercontent.com/6969966/83356680-58d15580-a370-11ea-9da8-14ce2aed8675.png)

2) It will probably require some kind of modification to the SVG files themselves. I'm not sure you can easily target just the borders of all SVGs in a generic way, unless they were made in a certain way, we need to investigate this with a small POC.

I thought maybe inverting the colors with CSS can be a solution, but it looks weird.

![image](https://user-images.githubusercontent.com/6969966/83356535-836ede80-a36f-11ea-8b76-6babe74df4f5.png)

2020-06-05 16:07 UTC, martinbedouret approved these changes

2020-06-05 16:07 UTC, merged