Intuitive board share
cboard-org/cboard pull request #826
Opened 2021-02-02 18:17 UTC by tomivm

1.Can I log in to my local server?
I modified 4 files, but I only edit BoardShare Files. it is because I did a "git add ." in cboard directory? How I can fix this? 
What's better? "now is working" or "wat's better" commits.
it was a better option to create a new component ButtonPublish, and with a prop "isPublic" return de correct button?

2021-02-05 14:27 UTC, martinbedouret commented
@tomivm I send you some initial feedback 

- Never commit lock files (package-lock.json, yarn.lock).
- Every time you have added a new string into a *.messages.js file, please add an entry into this file: https://github.com/cboard-org/cboard/blob/master/src/translations/src/cboard.json
- Please also update the title of the dialog to be 'share your board '

2021-02-05 15:37 UTC, martinbedouret requested changes

2021-02-07 20:52 UTC, tomivm commented
Hello! It's ready for a new review. Now I'm havings problems with the default messages of boardshare.messages.js . The component inspector of react shows the correct value. But its no reflecting in the modal.
![imagen](https://user-images.githubusercontent.com/21298844/107159067-362b1e00-698e-11eb-98e3-50df3e2aca37.png)

2021-02-09 15:39 UTC, martinbedouret approved these changes

2021-02-09 15:44 UTC, merged