update new content message adding kinds of notifications
cboard-org/cboard pull request #860
Opened 2021-03-09 01:11 UTC by tomivm

2021-03-11 03:01 UTC, sylvansson reviewed
This looks OK to me but I'm not a frontend developer so let's see what @martinbedouret thinks :-) 

I would suggest manually running Prettier on the files that you modified, because there are some minor styling issues like too much indentation. It usually runs automatically in a pre-commit hook but it might not be configured correctly on your machine.

2021-03-11 13:17 UTC, martinbedouret requested changes

2021-03-11 13:17 UTC, martinbedouret commented on src/components/Notifications/Notifications.reducer.js
> +const initialState = { message: '', open: false , kind : null };
use `undefined`, In JavaScript, undefined is a type, whereas null an object.

2021-04-11 01:04 UTC, martinbedouret approved these changes

2021-04-11 01:05 UTC, merged